let canvas = document.getElementById('myCanvas');
canvas.height = window.innerHeight -22;
canvas.width = window.innerWidth -10;
const maxWidth = canvas.width;
const maxHeight = canvas.height;
let n = parseInt(prompt(' Enter number of balls'));
let circles = new Array(n);
createCircles();
checkOverlappedCircles();
setInterval(moveCircles,20);